image: ghcr.io/cirruslabs/flutter:latest
stages:
  - tests
unit tests:
  stage: tests
  script:
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  tags:
    - docker
  artifacts:
    paths:
      - coverage
unit build: # Build the app for the web
  stage: tests
  script:
    - flutter build apk --release
  tags:
    - docker      
