image: ghcr.io/cirruslabs/flutter:latest
stages:
  - tests
unit tests:
  stage: build
  script:
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  tags:
    - flutter
  artifacts:
    paths:
      - coverage
