image: ghcr.io/cirruslabs/flutter:stable
test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test --machine > report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter
