image: ghcr.io/cirruslabs/flutter:latest
stages:
  - build
build: # Build the app for android
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build appbundle
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk  
  tags:
    - docker      
